data_source dataprodukt:
  type: bigquery
  connection:
    use_context_auth: True
  project_id: teamdagpenger-dev-885f
  dataset: dataprodukt

soda_cloud:
  host: sodacore-honeypot.dev.intern.nav.no
  api_key_id: 1
  api_key_secret: 2
