FROM eclipse-temurin:17-jre

RUN wget https://github.com/znsio/specmatic/releases/download/0.59.0/specmatic.jar \
        -O /specmatic.jar


COPY spec.yaml .

CMD ["java", "-jar", "/specmatic.jar", "stub", "spec.yaml"]
