---
openapi: "3.0.1"
info:
  title: "Contract for the petstore service"
  version: "1"
paths:
  /pets/{petid}:
    get:
      summary: "Should be able to get a pet by petId"
      parameters:
        - name: "petid"
          in: "path"
          required: true
          schema:
            type: "number"
          examples:
            200_OKAY:
              value: 1
      responses:
        "200":
          description: "Should be able to get a pet by petId"
          content:
            application/json:
              schema:
                required:
                  - "id"
                  - "name"
                  - "status"
                  - "type"
                properties:
                  id:
                    type: "number"
                  name:
                    type: "string"
                  type:
                    type: "string"
                  status:
                    type: "string"
              examples:
                200_OKAY:
                  value: '{any}'

  /api/command:
    post:
      summary: New scenario
      parameters:
      - name: host
        in: header
        required: true
        schema:
          type: string
      - name: content-type
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Command_RequestBody'
      responses:
        "200":
          description: New scenario
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Command_RequestBody:
      required:
      - apiKeyId
      - apiKeySecret
      - type
      properties:
        type:
          type: string
        apiKeyId:
          type: number
        apiKeySecret:
          type: number
