apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-data-sodacore-honeypot
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{image}}
  port: 9000
  replicas:
    max: 1
    min: 1
