apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-data-sodacore
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{image}}
  replicas:
    max: 1
    min: 1
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/bigquery.dataViewer
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/bigquery.jobUser

